[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
twitch = { path = "../twitch" }
utils = { path = "../utils" }
command-macro = { path = "../command-macro" }

# Async
async-trait = "0.1"

# Errors
anyhow = "1"
thiserror = "1"

# Logging
log = "0.4"
