default_job = "clippy"

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--color",
  "always",
  "--",
  "-W",
  "clippy::pedantic",
  "-W",
  "clippy::nursery",
  "-W",
  "clippy::unwrap_used",
  "-W",
  "clippy::expect_used",
]
need_stdout = false

[jobs.dev]
command = ["cargo", "run", "--color", "always", "-p", "bot"]
need_stdout = true
allow_warnings = true

[keybindings]
h = "job:clippy"
j = "job:dev"
c = "job:clippy"
d = "job:dev"
