---
version: "3"
name: clazza-bot
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: affax
      POSTGRES_PASSWORD: affax
      POSTGRES_DB: clazzabot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
